image:
    - Visual Studio 2017
    - Visual Studio 2022
    - Visual Studio 2019  
   

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc_tutorial
shallow_clone: true             

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    COMMS_BRANCH: v5.2.2
    CC_MQTT5_BRANCH: v2.6
    matrix:
        - CPP_STD: 17
        - CPP_STD: 20

matrix:
    fast_finish: false
    exclude:
        - image: Visual Studio 2017
          CPP_STD: 20                           
        
install:
    - call script\appveyor_install.bat
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - set COMMS_TAG=%COMMS_BRANCH%
    - set CC_MQTT5_TAG=%CC_MQTT5_BRANCH%
    - set COMMON_INSTALL_DIR=%BUILD_DIR%\install
    - set COMMON_BUILD_TYPE=%CONFIGURATION%
    - set COMMON_CXX_STANDARD=%CPP_STD%
    - set GENERATOR="%CMAKE_GENERATOR%"
    - set PLATFORM="%CMAKE_PLATFORM%"
    - call script\prepare_externals.bat

build_script:
    - echo ------------------------- Building Project -------------------------
    - cd %BUILD_DIR%
    - if NOT [%PLATFORM%] == [] set PLATFORM_PARAM=-A %PLATFORM%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%CMAKE_GENERATOR%" %PLATFORM_PARAM% -DBOOST_ROOT="%BOOST_DIR%" ^
        -DBoost_USE_STATIC_LIBS=ON -DCMAKE_CXX_STANDARD=%CPP_STD% -DCMAKE_INSTALL_PREFIX=install ^
        -DCMAKE_PREFIX_PATH="%COMMON_INSTALL_DIR%" -DCC_MQTT5_BUILD_UNIT_TESTS=ON -DCC_MQTT5_CLIENT_AFL_FUZZ=ON ^
        -DCC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES=%APPVEYOR_BUILD_FOLDER%/client/lib/script/BareMetalConfig.cmake
    - cmake --build . --config %CONFIGURATION% --target install --parallel %NUMBER_OF_PROCESSORS%


test_script:
    - echo ------------------------- Testing -------------------------
    - ctest -V    


